version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: vaudoise-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: monpassword
      POSTGRES_DB: vaudoise
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
