spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vaudoise
    username: postgres
    password: monpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8080
